src/Entity/PixaBay/Parameters/ImageOrientation.php
<?php

namespace ICS\WebapiBundle\Entity\PixaBay\Parameters;

use ReflectionClass;
use ICS\WebapiBundle\Entity\ApiParameter;

class ImageOrientation extends ApiParameter
{
    // Search image orientation
    const IMAGE_ORIETATION_ALL = "all";
    const IMAGE_ORIETATION_HORIZONTAL = "horizontal";
    const IMAGE_ORIETATION_VERTICAL = "vertical";

    public static function getBaseParameter()
    {
        return "IMAGE_ORIETATION";
    }

    /**
     * Get Image Type parameters list
     */
    public static function getParametersList(): array
    {
        $result = [];
        $oClass = new ReflectionClass(ImageOrientation::class);
        foreach ($oClass->getConstants() as $key => $cst) {

            $result[$cst] = ucfirst(strtolower(str_replace('IMAGE_ORIENTATION_', '', $key)));
        }

        return $result;
    }
}

src/Entity/PixaBay/Parameters/ImageType.php
<?php

namespace ICS\WebapiBundle\Entity\PixaBay\Parameters;

use ReflectionClass;
use ICS\WebapiBundle\Entity\ApiParameter;

class ImageType extends ApiParameter
{
    // Search image type
    const IMAGE_TYPE_ALL = "all";
    const IMAGE_TYPE_PHOTO = "photo";
    const IMAGE_TYPE_ILLUSTRATION = "illustration";
    const IMAGE_TYPE_VECTOR = "vector";

    /**
     * Get Image Type parameters list
     */
    public static function getParametersList(): array
    {
        $result = [];
        $oClass = new ReflectionClass(ImageType::class);
        foreach ($oClass->getConstants() as $key => $cst) {

            $result[$cst] = ucfirst(strtolower(str_replace('IMAGE_TYPE_', '', $key)));
        }

        return $result;
    }
}

src/Entity/PixaBay/Parameters/Language.php
<?php

namespace ICS\WebapiBundle\Entity\PixaBay\Parameters;

use ReflectionClass;
use ICS\WebapiBundle\Entity\ApiParameter;

class Language extends ApiParameter
{
    // Search language
    const LANGUAGE_cs = 'cs';
    const LANGUAGE_da = 'da';
    const LANGUAGE_DEUTCH = 'de';
    const LANGUAGE_ENGLISH = 'en';
    const LANGUAGE_SPANISH = 'es';
    const LANGUAGE_FRENCH = 'fr';
    const LANGUAGE_id = 'id';
    const LANGUAGE_ITALIAN = 'it';
    const LANGUAGE_HUNGARIAN = 'hu';
    const LANGUAGE_nl = 'nl';
    const LANGUAGE_no = 'no';
    const LANGUAGE_pl = 'pl';
    const LANGUAGE_pt = 'pt';
    const LANGUAGE_ro = 'ro';
    const LANGUAGE_sk = 'sk';
    const LANGUAGE_fi = 'fi';
    const LANGUAGE_sv = 'sv';
    const LANGUAGE_tr = 'tr';
    const LANGUAGE_vi = 'vi';
    const LANGUAGE_th = 'th';
    const LANGUAGE_bg = 'bg';
    const LANGUAGE_RUSSIAN = 'ru';
    const LANGUAGE_el = 'el';
    const LANGUAGE_JAPANASE = 'ja';
    const LANGUAGE_ko = 'ko';
    const LANGUAGE_zh  = 'zh';

    /**
     * Get Image Type parameters list
     */
    public static function getParametersList(): array
    {
        $result = [];
        $oClass = new ReflectionClass(Language::class);
        foreach ($oClass->getConstants() as $key => $cst) {

            $result[$cst] = ucfirst(strtolower(str_replace('LANGUAGE_', '', $key)));
        }

        return $result;
    }
}

src/Entity/PixaBay/Parameters/VideoPosterSize.php
<?php

namespace ICS\WebapiBundle\Entity\PixaBay\Parameters;

use ReflectionClass;
use ICS\WebapiBundle\Entity\ApiParameter;

/**
 * Vidéos poster picture size
 */
class VideoPosterSize extends ApiParameter
{
    const VIDEO_POSTER_SIZE_100x75 = '100x75';
    const VIDEO_POSTER_SIZE_200x150 = '200x150';
    const VIDEO_POSTER_SIZE_295x166 = '295x166';
    const VIDEO_POSTER_SIZE_640x360 = '640x360';
    const VIDEO_POSTER_SIZE_960x540 = '960x540';
    const VIDEO_POSTER_SIZE_1920x1080 = '1920x1080';

    /**
     * Get Image Type parameters list
     */
    public static function getParametersList(): array
    {
        $result = [];
        $oClass = new ReflectionClass(VideoPosterSize::class);
        foreach ($oClass->getConstants() as $key => $cst) {

            $result[$cst] = ucfirst(strtolower(str_replace('VIDEO_POSTER_SIZE_', '', $key)));
        }

        return $result;
    }
}

src/Entity/PixaBay/Response/PixaBayImage.php
<?php

namespace ICS\WebapiBundle\Entity\PixaBay\Response;


class PixaBayImage
{
    private $url;
    private $width;
    private $height;
    
    public function __construct(string $url,int $width,int $height)
    {
        $this->url = $url;
        $this->width = $width;
        $this->height = $height;
    }

	function getUrl():string {
		return $this->url;
	}

	function getWidth():int {
		return $this->width;
	}

	function getHeight():int {
		return $this->height;
	}

    function getSize(): string {
        return $this->width.'x'.$this->height;
    }
}

src/Entity/PixaBay/Response/PixaBayImageResponse.php
<?php

namespace ICS\WebapiBundle\Entity\PixaBay\Response;

use ICS\WebapiBundle\Entity\PixaBay\SearchOptions;

class PixaBayImageResponse
{
    private $id;
    private $pageUrl;
    private $type;
    private $tags;
    private $preview;
    private $webFormat;
    private $largeImage;
    private $views;
    private $downloads;
    private $collections;
    private $likes;
    private $comments;
    private $user;
	

    public function __construct(object $response)
    {
        $this->id = $response->id;
        $this->pageUrl = $response->pageURL;
        $this->type = $response->type;
        foreach(explode(',', $response->tags) as $tag)
        {
            $this->tags[]=trim($tag);
        }
        
        $this->preview = new PixaBayImage($response->previewURL, $response->previewWidth, $response->previewHeight);
        $this->webFormat = new PixaBayImage($response->webformatURL, $response->webformatWidth, $response->webformatHeight);
        $this->largeImage = new PixaBayImage($response->largeImageURL, $response->imageWidth, $response->imageHeight);
        $this->views = $response->views;
        $this->downloads = $response->downloads;
        $this->collections = $response->collections;
        $this->likes = $response->likes;
        $this->comments = $response->comments;
        $this->user = new PixaBayUser($response->user_id, $response->user, $response->userImageURL);
    }


	function getId() {
		return $this->id;
	}

	function getPageUrl() {
		return $this->pageUrl;
	}

	function getType() {
		return $this->type;
	}

	function getTags() {
		return $this->tags;
	}

	function getPreview() {
		return $this->preview;
	}

	function getWebFormat() {
		return $this->webFormat;
	}

	function getLargeImage() {
		return $this->largeImage;
	}


	function getViews() {
		return $this->views;
	}


	function getDownloads() {
		return $this->downloads;
	}

	function getCollections() {
		return $this->collections;
	}

	function getLikes() {
		return $this->likes;
	}

	function getComments() {
		return $this->comments;
	}

	function getUser() {
		return $this->user;
	}

	
}

src/Entity/PixaBay/Response/PixaBayImageSearchResponse.php
<?php

namespace ICS\WebapiBundle\Entity\PixaBay\Response;

use ICS\WebapiBundle\Entity\PixaBay\SearchOptions;

class PixaBayImageSearchResponse
{
    private $total;
    private $totalHits;
    private $images=[];

    private $limit;
    private $remaining;
    private $reset;

    private $options;

    public function __construct(string $jsonresponse, array $responseHeaders, SearchOptions $options)
    {
        $this->options =$options;
        $response = json_decode($jsonresponse);
        $this->total = $response->total;
        $this->totalHits = $response->totalHits;
        // Rate limit infos
        $this->remaining=$responseHeaders["x-ratelimit-remaining"][0];
        $this->limit=$responseHeaders["x-ratelimit-limit"][0];
        $this->reset=$responseHeaders["x-ratelimit-reset"][0];
        // Image Result
        foreach($response->hits as $img)
        {
            $this->images[]=new PixaBayImageResponse($img);
        }
    }

	function getTotal() {
		return $this->total;
	}

	function getTotalHits() {
		return $this->totalHits;
	}

	function getImages() {
		return $this->images;
	}

    function getLimit() {
		return $this->limit;
	}

	function getRemaining() {
		return $this->remaining;
	}

	function getReset() {
		return $this->reset;
	}

    function getNbPages() : int 
	{
        $nbPage = (int)($this->totalHits/$this->options->getPer_page());
        if(($this->totalHits/$this->options->getPer_page()) > $nbPage)
        {
            $nbPage++;
        }
		return  $nbPage;
	}

}

src/Entity/PixaBay/Response/PixaBayUser.php
<?php

namespace ICS\WebapiBundle\Entity\PixaBay\Response;


class PixaBayUser
{
    private $id;
    private $name;
    private $imageUrl;

    public function __construct(int $id, string $name, string $imageUrl)
    {
        $this->id = $id;
        $this->name = $name;
        $this->imageUrl = $imageUrl;
    }

    function getId()
    {
        return $this->id;
    }

    function getName()
    {
        return $this->name;
    }

    function getImageUrl()
    {
        return $this->imageUrl;
    }

    function getPageUrl()
    {
        return 'https://pixabay.com/fr/users/'.$this->getName().'-'.$this->getId();
    }
}

src/Entity/PixaBay/SearchOptions.php
<?php

namespace ICS\WebapiBundle\Entity\PixaBay;

use Symfony\Component\PropertyAccess\PropertyAccess;
use ReflectionClass;
use ICS\WebapiBundle\Entity\PixaBay\Parameters\Language;
use ICS\WebapiBundle\Entity\PixaBay\Parameters\ImageType;
use ICS\WebapiBundle\Entity\PixaBay\Parameters\ImageOrientation;

class SearchOptions
{
    /**
     * @var string
     */
    protected $key;
    /**
     * Search Query
     *
     * @var string
     */
    protected $q;
    /**
     * @var string
     */
    protected $lang = Language::LANGUAGE_ENGLISH;
    /**
     * @var string
     */
    protected $image_type = ImageType::IMAGE_TYPE_ALL;
    /**
     * @var string
     */
    protected $orientation = ImageOrientation::IMAGE_ORIETATION_ALL;
    /**
     * @var string
     */
    protected $category;
    /**
     * @var string
     */
    protected $min_width = 0;
    /**
     * @var string
     */
    protected $min_height = 0;
    /**
     * @var string
     */
    protected $colors;
    /**
     * @var string
     */
    protected $editors_choice = false;
    /**
     * @var bool
     */
    protected $safesearch = false;
    /**
     * @var string
     */
    protected $order;
    /**
     * @var int
     */
    protected $page = 1;
    /**
     * @var int
     */
    protected $per_page = 12;
    /**
     * @var bool
     */
    protected $pretty = false;

    public function __construct(string $apiKey)
    {
        $this->key = $apiKey;
    }

    public function getLang()
    {
        return $this->lang;
    }

    public function setLang($lang)
    {
        $this->lang = $lang;
        return $this;
    }

    public function getImage_type()
    {
        return $this->image_type;
    }

    public function setImage_type($image_type)
    {
        $this->image_type = $image_type;
        return $this;
    }

    public function getOrientation()
    {
        return $this->orientation;
    }

    public function setOrientation($orientation)
    {
        $this->orientation = $orientation;
        return $this;
    }

    public function getCategory()
    {
        return $this->category;
    }

    public function setCategory($category)
    {
        $this->category = $category;
        return $this;
    }

    public function getMin_width()
    {
        return $this->min_width;
    }

    public function setMin_width($min_width)
    {
        $this->min_width = $min_width;
        return $this;
    }

    public function getMin_height()
    {
        return $this->min_height;
    }

    public function setMin_height($min_height)
    {
        $this->min_height = $min_height;
        return $this;
    }

    public function getColors()
    {
        return $this->colors;
    }

    public function setColors($colors)
    {
        $this->colors = $colors;
        return $this;
    }

    public function getEditors_choice()
    {
        return $this->editors_choice;
    }

    public function setEditors_choice($editors_choice)
    {
        $this->editors_choice = $editors_choice;
        return $this;
    }

    public function getSafesearch()
    {
        return $this->safesearch;
    }

    public function setSafesearch($safesearch)
    {
        $this->safesearch = $safesearch;
        return $this;
    }

    public function getOrder()
    {
        return $this->order;
    }

    public function setOrder($order)
    {
        $this->order = $order;
        return $this;
    }

    public function getPage()
    {
        return $this->page;
    }

    public function setPage($page)
    {
        $this->page = $page;
        return $this;
    }

    public function getPer_page()
    {
        return $this->per_page;
    }

    public function setPer_page($per_page)
    {
        $this->per_page = $per_page;
        return $this;
    }

    public function getPretty()
    {
        return $this->pretty;
    }

    public function setPretty($pretty)
    {
        $this->pretty = $pretty;
        return $this;
    }

    public function __toString()
    {
        $finalUrlString = "";
        $oClass = new ReflectionClass(__CLASS__);
        $propertyAccessor = PropertyAccess::createPropertyAccessorBuilder()
            ->disableExceptionOnInvalidPropertyPath()
            ->getPropertyAccessor();
        foreach ($oClass->getProperties() as $property) {
            $finalUrlString .= $property->name . '=' . $propertyAccessor->getValue($this, $property->name) . '&';
        }

        $finalUrlString = substr($finalUrlString, 0, strlen($finalUrlString) - 1);
        dump($finalUrlString);
        return $finalUrlString;
    }

    public function getQ()
    {
        return $this->q;
    }

    public function setQ($q)
    {
        $this->q = $q;
        return $this;
    }

    public function getKey()
    {
        return $this->key;
    }
}

src/Controller/PixaBayController.php
<?php

namespace ICS\WebapiBundle\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use ICS\WebapiBundle\Service\PixaBayService;
use ICS\WebapiBundle\Entity\PixaBay\Parameters\ImageType;

class PixaBayController extends AbstractController
{
    /**
     * @Route("/pixabay/{imagePage}", name="ics-webapi-pixabay-homepage")
     */
    public function index(Request $request, PixaBayService $service, int $imagePage = 1)
    {
        $resultImages = [];

        $type = $request->get('type', ImageType::IMAGE_TYPE_ALL);
        $search = $request->get('search', '');

        if ($search != '') {
            $service->getSearchOptions()->setImage_type($type);
            $service->getSearchOptions()->setPage($imagePage);
            $service->getSearchOptions()->setSafesearch(true);
            $resultImages = $service->searchImages($search);
        }

        return $this->render("@Webapi\pixabay\pixabay.html.twig", [
            'imageTypes' => ImageType::getParametersList(),
            'selectedType' => $type,
            'search' => $search,
            'resultsImages' => $resultImages,
            'currentImagePage' => $imagePage,
        ]);
    }
}

templates/pixabay/pixabay.html.twig
{% extends "base.html.twig" %} {% block title %} PixaBay homepage {% endblock %} {% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h1>
                Welcome to PixaBay homepage
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <form id="searchForm" method="POST">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <select name="type" id="" class="form-select">
                            {% for itk,imageType in imageTypes %}
                            {% if selectedType == itk %}
                            {% set selected = 'selected' %}
                            {% else %}
                            {% set selected = '' %}
                            {% endif %}
                            <option value="{{ itk }}" {{ selected|default('') }}>
                                {{ imageType }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    <input type="text" name="search" class="form-control" value="{{ search }}" />
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% if search != '' %}
    <div class="row">
        <div class="col-12">
            <h2>
                Pictures















            </h2>
        </div>
    </div>
    {% for images in resultsImages.images|batch(6,'none') %}
    <div class="row my-3">
        {% for image in images %} {% if image=='none' %}
        <div class="col"></div>
        {% else %}
        <div class="col">
            <div class="card h-100">
                <img src="{{ image.webformat.url }}" alt="" class="card-img-top" />
                <div class="card-body">
                    <div class="row">
                        <div class="col-3">
                            <img src="{{ image.user.imageUrl }}" alt="User {{ image.user.name }}" class="rounded-circle img-fluid" />
                        </div>
                        <div class="col-9">
                            <a href="{{ image.user.pageUrl }}" target="_blank">
                                {{ image.user.name }}
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <i class="fa fa-tags"></i> Tags : {% for tag in image.tags %}
                    <a href="https://pixabay.com/fr/images/search/{{ tag }}/" class="badge bg-primary text-light">
                        {{ tag }}
                    </a> {% endfor %}
                </div>
                <div class="card-body text-center">
                    <div class="btn-group my-3">
                        <a class="btn btn-primary" href="{{ image.pageUrl }}" target="_blank">
                            <i class="fa fa-globe"></i>
                        </a>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="downloadMenuButton{{ image.id }}" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-download"></i>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="downloadMenuButton{{ image.id }}">
                                <li>
                                    <a class="dropdown-item" href="{{ image.preview.url }}" target="_blank">
                                        Preview ({{ image.preview.size }})
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{{ image.webformat.url }}" target="_blank">
                                        Web Format ({{ image.webformat.size }})
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{{ image.largeImage.url }}" target="_blank">
                                        Large Image ({{ image.largeImage.size }})
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %} {% endfor %}
    </div>
    {% endfor %}
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <ul class="pagination">
                {% if currentImagePage > 1 %}
                <li class="page-item">
                    <span class="page-link" href="{{ path('ics-webapi-pixabay-homepage',{imagePage: (currentImagePage - 1)}) }}">
                        Previous



                    </span>
                </li>
                {% endif %} {% for page in currentImagePage..currentImagePage + 5 %} {% if currentImagePage==page %} {% set active = 'active' %} {% else %} {% set active = '' %} {% endif %}
                <li class="page-item {{ active }}">
                    <span class="page-link" href="{{ path('ics-webapi-pixabay-homepage',{imagePage: page}) }}">
                        {{ page }}
                    </span>
                </li>
                {% endfor %} {% if resultsImages.nbPages > 10 %}
                <li class="page-item">
                    <span class="page-link disabled">
                        ...



                    </span>
                </li>
                {% endif %} {% for page in (resultsImages.nbPages - 5)..resultsImages.nbPages %} {% if currentImagePage==page %} {% set active = 'active' %} {% else %} {% set active = '' %} {% endif %}
                <li class="page-item {{ active }}">
                    <span class="page-link" href="{{ path('ics-webapi-pixabay-homepage',{imagePage: page}) }}">
                        {{ page }}
                    </span>
                </li>
                {% endfor %} {% if currentImagePage
                < resultsImages.nbPages %} <li class="page-item">
                    <span class="page-link" href="{{ path('ics-webapi-pixabay-homepage',{imagePage: (currentImagePage + 1)}) }}">
                        Next



                    </span>
                    </li>
                    {% endif %}
            </ul>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %} {% block stylesheets %}{% endblock %} {% block javascripts %}
<script>
    $(document).ready(function() {

        $('span.page-link').click(function(e) {


            $('#searchForm').attr('action', $(this).attr('href'));
            $('#searchForm').submit();

        });


    });
</script>
{% endblock %}